[workspace]
members = [
    "tracer-backend",
    "tracer-ui",
    "api-structs",
    "tracing-config-helper"
]


[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1.37"
tracing-subscriber = {version = "0.3.16", features=['env-filter', 'json']}
opentelemetry = {version= "0.19.0", features=['rt-tokio']}
opentelemetry-otlp = "0.12.0"
tracing-opentelemetry = "0.19.0"