$env.DOCKER_BIN_PATH = "/usr/local/bin/docker"
$env.DOCKER_COMPOSE_FILE_PATH = "./tracer.yml"
$env.FRONTEND_PUBLIC_URL_PATH_NO_TRAILING_SLASH =  "http://127.0.0.1:8081/"
$env.API_SERVER_URL_NO_TRAILING_SLASH = "http://127.0.0.1:4200"
$env.DATABASE_URL = "postgres://postgres:password@127.0.0.1:5435/postgres"
$env.ENVIRONMENT = "local"