services:
  gel:
    image: geldata/gel
    environment:
      GEL_SERVER_INSTANCE_NAME: tracer-db
      GEL_SERVER_PASSWORD: password
      GEL_SERVER_ADMIN_UI: enabled
      GEL_SERVER_SECURITY: insecure_dev_mode
    volumes:
      - "./dbschema:/dbschema"
      - "./gel/data:/var/lib/gel/data"
    ports:
      - "5657:5656"
  tracer-backend:
    build:
      dockerfile: ./Dockerfile
      args:
        API_SERVER_URL_NO_TRAILING_SLASH: "${API_SERVER_URL_NO_TRAILING_SLASH}"
    environment:
      RUST_LOG: "${RUST_LOG}"
      GEL_DSN: "${GEL_DSN}"
      GEL_CLIENT_SECURITY: "insecure_dev_mode"
    ports:
      - "4200:4200"


