services:
  gel:
    image: geldata/gel
    environment:
      GEL_SERVER_INSTANCE_NAME: tracer-db
      GEL_SERVER_PASSWORD: password
      GEL_SERVER_ADMIN_UI: enabled
      GEL_SERVER_SECURITY: insecure_dev_mode
    volumes:
      - "./dbschema:/dbschema"
      - "./gel/data:/var/lib/gel/data"
    ports:
      - "5656:5656"

