[package]
name = "gel-io-provider"
version = "0.1.0"
edition = "2024"

[dependencies]
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
tracer = { path = "../../tracer" }
tracked_error = { path = "../../tracked_error" }
uuid.workspace = true
gel-tokio.workspace = true
gel-protocol.workspace = true
thiserror.workspace = true
indexmap.workspace = true
