[package]
name = "tracer-backend"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json.workspace = true
uuid.workspace = true


gel-tokio.workspace = true
gel-protocol.workspace = true
gel-errors.workspace = true
pin-project-lite = "0.2.16"
my_macro = { path = "../my_macro" }
axum = { version = "0.8.3", features = ['query', 'macros'] }
tower-http = { version = "0.6.2", features = ['cors', 'fs', 'trace', 'decompression-br', 'compression-br', 'normalize-path'] }
valuable = { workspace = true }
tracing = { workspace = true, features = ["valuable"] }
valuable-derive.workspace = true
tokio = { version = "1", features = ["rt", "macros"] }
clap = { version = "4", features = ["derive", "env", "wrap_help"] }
dotenvy.workspace = true
thiserror = { workspace = true }
serde.workspace = true
reqwest.workspace = true
chrono.workspace = true

api-structs = { path = "../api-structs" }
tracked_error = { path = "../tracked_error", features = ["gel-tokio"] }
tower = "0.5.2"
http = "1"

[dependencies.tracing-config-helper]
version = "0.1.0"
path = "../tracing-config-helper"
