[package]
name = "tracer-backend"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json.workspace = true
uuid.workspace = true
tracing.workspace = true
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
gel-tokio.workspace = true
gel-protocol.workspace = true
gel-io-recorder = { path = "../gel-io-recorder" }
axum = { version = "0.8", features = ['query', 'macros'] }
tower-http = { version = "0.6", features = ['limit', 'cors', 'fs', 'trace', 'decompression-br', 'compression-br', 'normalize-path'] }
tokio = { version = "1", features = ["rt", "macros"] }
clap = { version = "4", features = ["derive", "env", "wrap_help"] }
recordable_params_macro = { path = "/Users/tiberiodarferreira/Documents/github/tracer/recordable_params_macro" }
dotenvy.workspace = true
thiserror = { workspace = true }
serde.workspace = true
reqwest.workspace = true
chrono.workspace = true
base64.workspace = true
indexmap.workspace = true
api-structs = { path = "../api-structs" }
tracked_error = { path = "../tracked_error", features = ["gel-tokio"] }
http = "1"
tower-service = "0.3.3"
axum-adapter = { path = "../axum-adapter" }

[dependencies.tracer]
version = "0.1.0"
path = "../tracer"
