[package]
name = "tracer-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json.workspace = true
uuid.workspace = true
parking_lot.workspace = true
deepsize.workspace = true

edgedb-tokio.workspace = true
#edgedb_codegen = { version = "0.2.1", features = ["query"] }
#edgedb-protocol = "0.6.1"

edgedb-derive = { git = "https://github.com/tiberiusferreira/edgedb-rust", branch = "StandaloneTransactions" }
edgedb_codegen = { git = "https://github.com/tiberiusferreira/edgedb_codegen", branch = "StandaloneTransactions", features = ['query'] }
edgedb-protocol = { git = "https://github.com/tiberiusferreira/edgedb-rust", branch = "StandaloneTransactions" }



axum = { version = "0.7.5", features = ['query', 'macros'] }
tower-http = { version = "0.6.2", features = ['cors', 'fs', 'trace', 'decompression-br', 'compression-br', 'normalize-path'] }
valuable = { workspace = true }
tracing = { workspace = true, features = ["valuable"] }
valuable-derive.workspace = true
frankenstein = { version = "0.37", default-features = false, features = ['async-http-client'] }
tokio = { version = "1", features = ["rt", "macros"] }
clap = { version = "4", features = ["derive", "env", "wrap_help"] }
dotenvy.workspace = true
thiserror = { workspace = true }
sqlx.workspace = true
futures = "0.3"
serde.workspace = true
base64.workspace = true
reqwest.workspace = true
chrono.workspace = true

api-structs = { path = "../api-structs" }
tracked_error = { path = "../tracked_error" }
tower = "0.4.13"
http = "1.1.0"

[dependencies.tracing-config-helper]
version = "0.1.0"
path = "../tracing-config-helper"


[features]
query = []
default = ["query"]
