[package]
name = "tracer"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde.workspace = true
indexmap.workspace = true
reqwest.workspace = true
brotli.workspace = true
tokio.workspace = true
thiserror.workspace = true
api-structs = { path = "../api-structs" }
tracked_error = { path = "../tracked_error", features = ["reqwest"] }
futures.workspace = true
serde_json.workspace = true
pprof = { version = "0.15", features = ["flamegraph", "frame-pointer", "prost-codec"] }
base64.workspace = true
chrono.workspace = true
tracing = "0.1"

pin-project-lite = "0.2.16"
uuid.workspace = true