create database tracer;

alter database tracer set default_statistics_target = 10000;
alter database tracer set plan_cache_mode = 'force_custom_plan';
alter database tracer set work_mem = '16MB';


-- -- -- -- schema -- -- -- --
create table service
(
    id   int primary key generated by default as identity,
    env  text not null check (length(env) <= 256),
    name text not null check (length(name) <= 256),
    constraint service_unique_by_env_plus_name unique (env, name)
);


create table service_rust_log_setting
(
    service_id int primary key not null references service (id),
    rust_log   text            not null check ( length(rust_log) <= 1024 ),
    created_at timestamptz     not null default now()
);



create table instance
(
    id            int primary key generated by default as identity,
    global_id     uuid        not null,
    service_id    int         not null references service (id),
    registered_at timestamptz not null default now(),
    constraint instance_unique_by_external_id unique (global_id)
);

create table instance_update
(
    instance_id              int         not null references instance (id),
    update_id                int         not null check ( update_id >= 0 ),
    export_buffer_size_bytes bigint      not null check ( export_buffer_size_bytes >= 0 ),
    created_at               timestamptz not null default now(),
    primary key (instance_id, update_id)
);


create table instance_latest_log_filter_and_cpu_profile
(
    instance_id int primary key not null references instance (id),
    log_filter  text check ( length(log_filter) <= 1024),
    cpu_profile bytea check ( length(cpu_profile) <= 15728640), -- 15MB
    updated_at  timestamptz     not null default now()
);

create table trace
(
    instance_id        int         not null,
    trace_id           int         not null,
    instance_update_id int         not null,
    created_at         timestamptz not null default now(),
    primary key (instance_id, trace_id),
    foreign key (instance_update_id, instance_id) references instance_update (update_id, instance_id)
);


create table trace_cache
(
    instance_id         int     not null,
    trace_id            int     not null,
    http_method         text check ( http_method in ('options',
                                                     'get',
                                                     'post',
                                                     'put',
                                                     'delete',
                                                     'head',
                                                     'trace',
                                                     'connect',
                                                     'patch') ),
    http_path           text check ( length(http_path) <= 256 ),
    http_status         int check ( http_status <= 600 ),
    stored_spans_count  int     not null check ( stored_spans_count >= 0 ),
    stored_events_count int     not null check ( stored_events_count >= 0 ),
    stored_bytes_count  int     not null check ( stored_bytes_count >= 0 ),
    warnings_count      int     not null check ( warnings_count >= 0 ),
    has_errors          boolean not null,
    primary key (instance_id, trace_id),
    foreign key (instance_id, trace_id) references trace (instance_id, trace_id)
);

create table span
(
    instance_id        int       not null,
    trace_id           int       not null,
    span_id            int       not null,
    instance_update_id int       not null,
    parent_id          int,
    name               text check (
        length(name) <= 256
        )                        not null,
    created_at         timestamp not null,
    duration_nanos     bigint    not null,
    duration_is_final  boolean   not null,
    module             text      null,
    filename           text      null,
    line               int       null,
    primary key (instance_id, trace_id, span_id),
    -- parent_id must reference same trace
    foreign key (instance_id, trace_id, parent_id)
        references span (instance_id, trace_id, span_id)
        on delete cascade,
    foreign key (instance_id, trace_id) references trace (instance_id, trace_id),
    foreign key (instance_update_id, instance_id) references instance_update (update_id, instance_id)
);

-- -- making sure there is a single root per trace
create unique index single_root_per_trace
    on span (instance_id, trace_id, parent_id)
    nulls not distinct
    where parent_id is null;

create table span_links
(
    instance_id          int not null,
    trace_id             int not null,
    span_id              int not null,
    links_to_instance_id int not null,
    links_to_trace_id    int not null,
    links_to_span_id     int not null,
    primary key (instance_id, trace_id, span_id, links_to_instance_id, links_to_trace_id, links_to_span_id)
);



create table span_attributes
(
    instance_id int   not null,
    trace_id    int   not null,
    span_id     int   not null,
    name        text check (
        length(name) <= 256
        )             not null,
    value       jsonb not null
        check (
            length(value::text) <= 1572864
            ),
    primary key (instance_id, trace_id, span_id, name)
);


create table event
(
    instance_id        int       not null,
    trace_id           int       not null,
    span_id            int       not null,
    event_id           int       not null,
    instance_update_id int       not null,
    logged_at          timestamp not null,
    message            text check (
        length(message) <= 1572864
        )                        null,
    module             text      null,
    filename           text      null,
    line               int       null,
    severity           text check (
        severity in ('trace',
                     'debug',
                     'info',
                     'warn',
                     'error')
        )                        not null,
    primary key (instance_id, trace_id, span_id, event_id),
    foreign key (instance_id, trace_id, span_id) references span (instance_id, trace_id, span_id) on delete cascade,
    foreign key (instance_update_id, instance_id) references instance_update (update_id, instance_id)
);

create table event_attributes
(
    instance_id int not null,
    trace_id    int not null,
    span_id     int not null,
    event_id    int not null,
    name        text check (
        length(name) <= 256
        )           not null,
    value       jsonb
        check (
            length(value::text) <= 1572864
            )
                    not null,
    primary key (instance_id, trace_id, span_id, event_id, name),
    foreign key (instance_id, trace_id, span_id, event_id) references event (instance_id, trace_id, span_id, event_id) on delete cascade
);

create table series
(
    id                      serial primary key,
    name                    varchar(150) not null,
    sql                     text         not null check ( length(sql) <= 16384 ),
    check_window            int check ( check_window >= 0 ),
    max_missing_data_points int check ( max_missing_data_points >= 0 ),
    max_value_threshold     int,
    min_value_threshold     int,
    unique (name)
);


create table series_alert_check
(
    id                int primary key generated by default as identity,
    series_id         int         not null references series (id),
    alert_message     text        not null check (length(alert_message) < 16384),
    notification_sent boolean              default false,
    created_at        timestamptz not null default now()
);



create table telegram_alert_config
(
    id                       int primary key generated by default as identity,
    api_key                  varchar(150)                                not null,
    chat_id                  varchar(150)                                not null,
    min_alert_period_seconds int check ( min_alert_period_seconds >= 0 ) not null default 3600,
    enabled                  boolean                                     not null default true,
    unique (api_key, chat_id)
);


insert into series (name, sql, check_window, max_missing_data_points, max_value_threshold, min_value_threshold)
VALUES ('tracer local export buffer size', 'with time_axis as (SELECT date_bin(''90 sec''::interval, time_interval, ''epoch'') as time
                   FROM generate_series(date_subtract(NOW(), ''1 hour''::interval), NOW(),
                                        ''90 sec''::interval) as time_interval
                   order by time desc
                   limit 5000),
     data_axis as (SELECT date_bin(''90 sec''::interval, instance_update.created_at, ''epoch'') as time,
                          max(instance_update.export_buffer_size_bytes)                     as data,
                          service.name                                                      as service_name
                   FROM instance_update
                            inner join instance on instance.id = instance_update.instance_id
                            inner join service on service.id = instance.service_id
                   where service.name = ''tracer-backend''
                     and env = ''local''
                   GROUP BY time, service_name)
select time_axis.time, data_axis.data, data_axis.service_name as series_id
from time_axis
         left join data_axis on data_axis.time = time_axis.time
ORDER BY time desc;', 5, 3, 1000000, 0);


/*
with time_axis as (SELECT date_bin('90 sec'::interval, time_interval, 'epoch') as time
                   FROM generate_series(date_subtract(NOW(), '1 hour'::interval), NOW(),
                                        '90 sec'::interval) as time_interval
                   order by time desc
                   limit 5000),
     data_axis as (SELECT date_bin('90 sec'::interval, instance_update.created_at, 'epoch') as time,
                          max(instance_update.export_buffer_size_bytes)                     as data,
                          service.name                                                      as service_name
                   FROM instance_update
                            inner join instance on instance.id = instance_update.instance_id
                            inner join service on service.id = instance.service_id
                   where service.name = 'tracer-backend'
                     and env = 'local'
                   GROUP BY time, service_name)
select time_axis.time, data_axis.data, data_axis.service_name as series_id
from time_axis
         left join data_axis on data_axis.time = time_axis.time
ORDER BY time desc;
*/
