create database tracer;

alter database tracer set default_statistics_target = 1000;
alter database tracer set plan_cache_mode = 'force_custom_plan';
alter database tracer set work_mem = '8MB';


-- -- -- -- schema -- -- -- --
create table service
(
    id   int primary key generated by default as identity,
    env  text not null check (length(env) <= 256),
    name text not null check (length(name) <= 256),
    constraint service_unique_by_env_plus_name unique (env, name)
);


create table service_rust_log_setting
(
    service_id int primary key not null references service (id),
    rust_log   text            not null check ( length(rust_log) <= 1024 ),
    updated_at timestamptz     not null default now()
);

create table instance
(
    id         int primary key generated by default as identity,
    global_id  uuid        not null,
    service_id int         not null references service (id),
    created_at timestamptz not null default now(),
    constraint instance_unique_by_external_id unique (global_id)
);

create table instance_update
(
    id          int primary key generated by default as identity,
    instance_id int         not null references instance (id),
    created_at  timestamptz not null default now()
);
create unique index instance_update_id_instance_id_unique on instance_update (id, instance_id);
comment on index instance_update_id_instance_id_unique is
    'Used to be able to use (id, instance_id) as FK to instance_update and ensure an entity
 can only be linked to an update from the same instance it came from originally';


create table instance_latest_rust_log_and_cpu_profile
(
    instance_id int primary key not null references instance (id),
    rust_log    text check ( length(rust_log) <= 1024),
    cpu_profile bytea check ( length(cpu_profile) <= 15728640), -- 15MB
    updated_at  timestamptz     not null default now()
);

create table trace
(
    id                         int primary key generated by default as identity,
    instance_id                int         not null,
    instance_internal_trace_id int         not null check ( instance_internal_trace_id >= 0 ),
    instance_update_id         int         not null,
    created_at                 timestamptz not null default now(),
    unique (instance_id, instance_internal_trace_id),
    foreign key (instance_update_id, instance_id) references instance_update (id, instance_id),
    unique (id, instance_id)
);
comment on column trace.instance_internal_trace_id is 'Only unique per-instance';


create table trace_cache
(
    trace_id            int primary key not null references trace (id),
    http_method         text check ( http_method in ('get', 'post', 'put') ),
    http_path           text check ( length(http_path) <= 256 ),
    http_status         int check ( http_status <= 600 ),
    stored_spans_count  int             not null check ( stored_spans_count >= 0 ),
    stored_events_count int             not null check ( stored_events_count >= 0 ),
    stored_bytes_count  int             not null check ( stored_bytes_count >= 0 ),
    warnings_count      int             not null check ( warnings_count >= 0 ),
    has_errors          boolean         not null
);

create table span
(
    id                        int primary key generated by default as identity,
    instance_id               int       not null,
    trace_id                  int       not null,
    instance_internal_span_id int       not null,
    instance_update_id        int       not null,
    parent_id                 int,
    name                      text check (
        length(name) <= 256
        )                               not null,
    entered_at                timestamp not null,
    duration_nanos            bigint    not null,
    duration_is_final         boolean   not null,
    module                    text      null,
    filename                  text      null,
    line                      int       null,
    unique (trace_id, instance_internal_span_id),
    unique (id, instance_id),
    unique (trace_id, id),
    -- parent_id must reference same trace
    foreign key (trace_id, parent_id)
        references span (trace_id, id)
        on delete cascade,
    foreign key (instance_id, trace_id) references trace (instance_id, id),
    foreign key (instance_update_id, instance_id) references instance_update (id, instance_id)
);

-- -- making sure there is a single root per trace
create unique index single_root_per_trace
    on span (trace_id, parent_id)
    nulls not distinct
    where parent_id is null;

create table span_links
(
    id          int primary key references span (id),
    links_to_id int primary key references span (id)
);


create table span_key_value
(
    span_id int  not null references span (id),
    key     text check (
        length(key) <= 256
        )        not null,
    value   text not null,
    primary key (span_id, key)
);


create table event
(
    id                 int primary key generated by default as identity,
    span_id            int       not null,
    instance_id        int       not null,
    instance_update_id int       not null,
    logged_at          timestamp not null,
    message            text check (
        length(message) <= 1572864
        )                        null,
    module             text      null,
    filename           text      null,
    line               int       null,
    severity           text check (
        severity in ('trace',
                     'debug',
                     'info',
                     'warn',
                     'error')
        )                        not null,
    foreign key (span_id, instance_id) references span (id, instance_id) on delete cascade,
    foreign key (instance_update_id, instance_id) references instance_update (id, instance_id)
);

create table event_key_value
(
    event_id int not null
        references event (id)
            on delete cascade,
    key      text check (
        length(key) <= 256
        )        not null,
    value    text
        check (
            length(value) <= 1572864
            )
                 not null,
    primary key (event_id, key)
);


-- create table orphan_event
-- (
--     id                 int primary key generated by default as identity,
--     instance_id        int         not null,
--     instance_update_id int         not null,
--     logged_at          timestamptz not null,
--     severity           text check (
--         severity in ('trace',
--                      'debug',
--                      'info',
--                      'warn',
--                      'error')
--         )                          not null,
--     message            text check (
--         length(message) <= 1572864
--         )                          null,
--     foreign key (instance_update_id, instance_id) references instance_update (id, instance_id)
-- );
--
--
-- create table orphan_event_key_value
-- (
--     orphan_event_id bigint
--         references orphan_event (id) on delete cascade
--                          not null,
--     key             text not null
--         check (
--             length(key) <= 256
--             ) not null,
--     value           text
--         check (
--             length(value) <= 1572864
--             )
--                          not null,
--     primary key (orphan_event_id, key)
-- );
--
--
--
--
--
--
-- create table service_wide_alert_config
-- (
--     service_id         int primary key                       not null references service (id),
--     min_instance_count int check ( min_instance_count >= 0 ) not null default 0,
--     max_active_traces  int check ( max_active_traces >= 0 )  not null default 1000
-- );
--
--
-- create table trace_wide_alert_config
-- (
--     service_id                          int primary key not null references service (id),
--     max_trace_duration_ms               int             not null default 1000000,
--     max_traces_with_warning_percentage  int             not null default 100,
--     percentage_check_time_window_secs   int             not null default 60,
--     percentage_check_min_number_samples int             not null default 5
-- );
--
--
-- create table trace_wide_http_alert_config_overwrite
-- (
--     service_id                         int  not null references service (id),
--     http_path                          text not null check ( length(http_path) <= 256 ),
--     http_method                        text not null check ( http_method in ('get', 'post', 'put') ),
--     max_traces_with_warning_percentage int  not null default 100,
--     max_trace_duration_ms              int  not null default 1000000,
--     primary key (service_id, http_path, http_method)
-- );
--
--
--
-- create table trace_wide_custom_alert_config_overwrite
-- (
--     service_id                         int  not null references service (id),
--     top_level_span_name                text not null check (
--         length(top_level_span_name) <= 256
--         ),
--     max_traces_with_warning_percentage int  not null default 100,
--     max_trace_duration_ms              int  not null default 1000000,
--     primary key (service_id, top_level_span_name)
-- );
--
-- create table alert_check
-- (
--     id         serial primary key,
--     started_at timestamptz not null,
--     ended_at   timestamptz not null
-- );
-- comment on table alert_check is 'Before checking for alerts, services should acquire a lock on this table, to prevent multiple checks';
--
-- create table alert_check_alerts
-- (
--     id             serial primary key,
--     alert_check_id int  not null references alert_check (id),
--     alert          text not null check ( length(alert) <= 2048 ),
--     send_error     text check ( length(send_error) <= 4096 )
-- );
--
--
-- create table slack_alert_config
-- (
--     id                       serial primary key,
--     bot_user_oauth_token     varchar(150)                               not null,
--     channel_id               varchar(150)                               not null,
--     min_alert_period_seconds int check ( min_alert_period_seconds > 0 ) not null default 3600,
--     enabled                  boolean                                    not null,
--     unique (bot_user_oauth_token, channel_id)
-- );

--
--
-- create table telegram_alert_config
-- (
--     id                       serial primary key,
--     api_key                  varchar(150) not null,
--     chat_id                  varchar(150) not null,
--     min_alert_period_seconds p_i32        not null default 3600,
--     enabled                  boolean      not null,
--     unique (api_key, chat_id)
-- );
--
-- create table telegram_alert
-- (
--     telegram_alert_config int           not null references telegram_alert_config (id),
--     notification          varchar(2048) not null,
--     send_error            varchar(4096),
--     created_at            timestamp     not null default NOW(),
--     primary key (telegram_alert_config, created_at)
-- );
