on:
  push
jobs:
  my_job:
    name: build docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        FRONTEND_PUBLIC_URL_PATH_NO_TRAILING_SLASH: "http://127.0.0.1:4200"
        API_SERVER_URL_NO_TRAILING_SLASH: "http://127.0.0.1:4200"
      run: |
        docker buildx create --use --driver=docker-container && \
        docker buildx build . --file Dockerfile --tag $DOCKER_USER/tracer:latest \
        --output type=docker \
        --cache-to type=gha,mode=max --cache-from type=gha \
        --build-arg API_SERVER_URL_NO_TRAILING_SLASH=$API_SERVER_URL_NO_TRAILING_SLASH \
        --build-arg FRONTEND_PUBLIC_URL_PATH_NO_TRAILING_SLASH=$FRONTEND_PUBLIC_URL_PATH_NO_TRAILING_SLASH
    - name: Docker Push
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
      run: docker push $DOCKER_USER/tracer:latest
